version: '2'
services:
    db:
        image: mysql:latest
        restart: always
        container_name: myphpapp-db
        environment:
            MYSQL_ROOT_PASSWORD: guest
            MYSQL_DATABASE: test
    
